version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - 6379:6379
